### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by YannCaron** [troyedwardsjr/phaser3-typescript-webpack#4]
When running the start page, with no code modification, I get this error :

``` bash
ERROR in ./src/main.ts
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cyann/projects/web/kids-lab.io/phaser3-typescript-webpack/node_modules/@babel/core/lib/index.js:147:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cyann/projects/web/kids-lab.io/phaser3-typescript-webpack/node_modules/babel-loader/lib/transform.js:1:75)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cyann/projects/web/kids-lab.io/phaser3-typescript-webpack/node_modules/babel-loader/lib/cache.js:24:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cyann/projects/web/kids-lab.io/phaser3-typescript-webpack/node_modules/babel-loader/lib/index.js:9:13)
    at Module._compile (module.js:410:26)
 @ multi ./src/main.ts

```

**Comment by troyedwardsjr** [comment]
Just did a fresh clone and it's working fine for me on Ubuntu. `npm install` & `npm run dev`.

**Comment by YannCaron** [comment]
Oh yes, forget this issue, my nodejs was an old installation (4.6.2). I certainly faced a linux PPA problem.
Now with the version 10 of node, it's works like a charm.

Thanks for your help and sorry for the disturbance.
